### PR TITLE
Do not add issues for Docker Steps

### LINKED ISSUE #348: Do not add issues for Docker Steps
checkout: #347

### PR DESCRIPTION
**Pull request by Devils-Knight**
Fixes #348

### CODE REVIEW

**Comment by varunsh-coder** [comment]
@Devils-Knight I am now thinking if we should have a `known-issue` error for this case?

**Comment by Devils-Knight** [comment]
> @Devils-Knight I am now thinking if we should have a `known-issue` error for this case?

@varunsh-coder I think it would be better if we add `known-issue` for this case as there might be other permissions associated with that docker action and if in case the workflow fails because of missing permissions, the `repo owner` would be aware of error.

I have added the `Known-Issue` for docker action, please review the changes.

**Comment by varunsh-coder** [comment]
@Devils-Knight please add test case for this

**Comment by varunsh-coder** [comment]
@Devils-Knight we need to think more about it. In the test case that is added, github_token is not being used. So we can calculate permissions for it. We already have a case where github_token is in action input or in env variable for run cases.  So we could treat `docker://` as `run` case since we don't know what is happening in the docker image. Let us discuss offline.

**Comment by Devils-Knight** [comment]
> @Devils-Knight we need to think more about it. In the test case that is added, github_token is not being used. So we can calculate permissions for it. We already have a case where github_token is in action input or in env variable for run cases. So we could treat `docker://` as `run` case since we don't know what is happening in the docker image. Let us discuss offline.

@varunsh-coder added the logic for docker action, please review the changes.

**Pull request merged**
