### PR TITLE
Modifying permissions.go to solve issue159

### PR DESCRIPTION
**Pull request by h0x0er**
Issue #159

### CODE REVIEW

**Comment by varunsh-coder** [comment]
@h0x0er you still have to make changes for the job level permissions, right? If job level permissions are `contents: read` only, then they should not be included.

**Comment by h0x0er** [comment]
@varunsh-coder

**Comment by h0x0er** [comment]
> Please create the pull request into the `int` branch. That is the integration testing branch. Changes can be tested here: https://int1.stepsecurity.io before releasing to prod.

@varunsh-coder Should I close this PR before creating a new PR into `int` branch  ?

**Comment by h0x0er** [comment]
> @h0x0er you still have to make changes for the job level permissions, right? If job level permissions are `contents: read` only, then they should not be included.

@varunsh-coder Yes, you are right i still have to fix the 2nd point.

**Comment by h0x0er** [comment]
@varunsh-coder ok got it.

**Pull request closed without merging**
